### PR TITLE
Fix up some m/s specific coding

### PR DESCRIPTION
**Pull request by ThosRTanner**

### CODE REVIEW

**Comment by TanninOne** [comment]
Why is the template specialization M/S specific? Tbh I'm not a big fan of mixing function templates and overloading.
It requires the reader two know how/when overloading vs. spezialization are resolved and if there is a tiny difference in signatures you end up calling the generic template-variant accidentally. With the template specialization you get a compiler error if the signatures don't match.

**Comment by ThosRTanner** [comment]
According to clang, explicit template specialisation of a templated class method is a microsoft extension. I'm not sure why but it is.

Whilst I realise that this is unlikely to be compiled with anything other than microsoft, I thought it'd be cleaner to be portable. (Also it gets rid of the rather icky declaration in the source code as a bonus).

After some digging around, I found the standard compliant declaration - thought it has to be _outside_ the class like this:

```
class GamebryoSaveGame { ... };
template <> void GamebryoSaveGame::FileWrapper::read<QString>(QString &);
```

which also doesn't require the declspec bit in the implementation. I can change it to that if you'd prefer.

**Comment by TanninOne** [comment]
Yeah, I'd prefer that variant. Thanks!

**Comment by ThosRTanner** [comment]
There we go

**Pull request merged**
